### ISSUE TITLE
Error running example on Getting started documentation

### ISSUE THREAD

**Issue by olivertomic** [Sulstice/cocktail-shaker#109]
This comment comes out of my JOSS review.

I installed cocktail shaker successfully (pip install) on Windows 10. When I tried to run the simple example on the Getting started page of the documentation (https://cocktail-shaker.readthedocs.io/en/latest/guide/quickstart.html), I get the following error.

(joss) C:\Users\olive\Google Drive\Work\joss>python test01.py
Traceback (most recent call last):
  File "test01.py", line 10, in <module>
    from cocktail_shaker import PeptideBuilder
ImportError: cannot import name 'PeptideBuilder' from 'cocktail_shaker' (C:\Users\olive\anaconda3\envs\joss\lib\site-packages\cocktail_shaker\__init__.py)

**Comment by Sulstice** [comment]
Ah this might have been an update that seeped its way into the build somewhere.  Thanks for letting me know I will update shortly today and release a new build.

**Comment by Sulstice** [comment]
I've identified the problem: __init__.py was not updated in this release appropriately, the class name changed from PeptideMolecule to PeptideBuilder. Issuing a new release patch.

**Comment by Sulstice** [comment]
Fixed and patched! in v1.1.1
