### ISSUE TITLE
Another error when running code example on Getting Started page

### ISSUE THREAD

**Issue by olivertomic** [Sulstice/cocktail-shaker#125]
Hi Suliman, 

thank you for fixing the error.

i have installed now v1.1.1 and re-run the same example as in the previous issue:
https://github.com/Sulstice/cocktail-shaker/issues/109 

This time get another error:

Generating Compounds...
Traceback (most recent call last):
  File "test01.py", line 13, in <module>
    combinations = cocktail.shake()
  File "C:\Users\olive\anaconda3\envs\joss2\lib\site-packages\cocktail_shaker\functional_group_enumerator.py", line 107, in shake
    for i in progressbar.progressbar(range(len(combinations))):
TypeError: 'module' object is not callable

**Comment by Sulstice** [comment]
Hi @olivertomic Hmm I think I included both the progressbar and progressbar2 module in the requirements.txt. I'll try removing it today and see if that resolves the issue

**Comment by olivertomic** [comment]
@Sulstice 
I checked my virtual environment and I see that both progressbar and progressbar2 are installed. The following versions are installed:

progressbar==2.5
progressbar2==3.47.0

**Comment by Sulstice** [comment]
@olivertomic 

So the progressbar2 has a progressbar module (I know......) so there is a conflict of progressbar modules with both being present. 

try doing pip uninstall progressbar and keep the progressbar2

**Comment by olivertomic** [comment]
Thanks @Sulstice 

I uninstalled progressbar, kept progressbar2 and tried again. Now I get the following:

Generating Compounds...
Traceback (most recent call last):
  File "test01.py", line 13, in <module>
    combinations = cocktail.shake()
  File "C:\Users\olive\anaconda3\envs\joss2\lib\site-packages\cocktail_shaker\functional_group_enumerator.py", line 107, in shake
    for i in progressbar.progressbar(range(len(combinations))):
AttributeError: module 'progressbar' has no attribute 'progressbar'

**Comment by Sulstice** [comment]
Hmmmm I did just try pip installing progressbar most recent version so nothing in their API has changed. I will have to check this deeper after work ~6 hours (still morning over here)

**Comment by Sulstice** [comment]
@olivertomic So I believe this error is within the setup.py of the installed version that I have at the time 3.47.0 for progressbar2.  A lot of the advice I saw was to implement a new class object from progress bar called ProgressBar (I know....). 

So I'm going to tackle this in steps:
1.) Cocktail Shaker is being released with a hot-fix where I remove the dependency (it was more aesthetic than functionality) -> v1.1.4. 
2.) Long-term fix is to adopt to the new progressbar version and adjust cocktail shaker to wrap it in. 

Try reinstalling cocktail shaker and see if you can follow through with the example (verified locally on a new virtual environment)

**Comment by olivertomic** [comment]
@Sulstice , thanks a lot for the fix. The example now works as expected.

**Comment by Sulstice** [comment]
:)
