### ISSUE TITLE
Error in documentation example for FileWriter module

### ISSUE THREAD

**Issue by olivertomic** [Sulstice/cocktail-shaker#130]
Running the code on this part of the documentation

https://cocktail-shaker.readthedocs.io/en/latest/guide/file_handling.html

>>> from cocktail_shaker import Cocktail, FileWriter
>>> from cocktail_shaker import PeptideBuilder
>>> peptide_backbone = PeptideBuilder(2)
>>> cocktail = Cocktail(peptide_backbone,ligand_library = ['Br', 'I'])
>>> combinations = cocktail.shake()
>>> FileWriter('new_compounds', combinations, '.sdf')

gives this error:

(joss3) C:\Users\olive\Google Drive\Work\joss>python test06.py
Generating 2 Compounds...
Traceback (most recent call last):
  File "test06.py", line 6, in <module>
    FileWriter('new_compounds', combinations, '.sdf')
  File "C:\Users\olive\anaconda3\envs\joss3\lib\site-packages\cocktail_shaker\file_handler.py", line 49, in __init__
    raise FileNotSupportedError(message='Cocktail Shaker does not support that file format')
TypeError: __init__() missing 1 required positional argument: 'errors'

I also get exactly the same error for the next example.

**Comment by Sulstice** [comment]
Hmmm I am at currently work but I think try putting 'sdf' rather than '.sdf', my example probably has that error :'(. I'll have to fix some things in the docs.

**Comment by Sulstice** [comment]
Just confirmed this an issue in the documentation where I added the "." in the file extension this should be just "sdf".
