### ISSUE TITLE
NameError in pickle example in documentation

### ISSUE THREAD

**Issue by olivertomic** [Sulstice/cocktail-shaker#131]
Running the example for `store_as_pickle` method in the documentation
https://cocktail-shaker.readthedocs.io/en/latest/guide/cocktail.html

>>> from cocktail_shaker import Cocktail
>>> from cocktail_shaker import PeptideBuilder
>>> peptide_molecule = PeptideBuilder(2)
>>> cocktail = Cocktail(peptide_molecule, ligand_library=['Br', 'I'])
>>> print (cocktail.shake(store_as_pickle= True))
>>> cocktail_shaker.pickle

I get the following NameError

(joss3) C:\Users\olive\Google Drive\Work\joss>python test09.py
Generating 2 Compounds...
saving result to cache 'cocktail_shaker.pickle'
['NC(Br)C(=O)NC(I)C(=O)NCC(=O)O', 'NC(I)C(=O)NC(Br)C(=O)NCC(=O)O']
Traceback (most recent call last):
  File "test09.py", line 6, in <module>
    cocktail_shaker.pickle
NameError: name 'cocktail_shaker' is not defined

I would guess this is due to invoking a class or method before it got defined?

**Comment by Sulstice** [comment]
This is me not being clear in what the output should be. A pickle file should be produced with the name "cocktail_shake.pickle", I'll fix this in the documentation as well.
