### ISSUE TITLE
First enumerate example returns different output

### ISSUE THREAD

**Issue by olivertomic** [Sulstice/cocktail-shaker#132]
When testing the first example of the enumerate function in the documentation

https://cocktail-shaker.readthedocs.io/en/latest/guide/cocktail.html

>>> from cocktail_shaker import Cocktail
>>> from cocktail_shaker import PeptideBuilder   >>> peptide_backbone = PeptideBuilder(2)
>>> cocktail = Cocktail(peptide_backbone,ligand_library = ['Br', 'I'])
>>> combinations = cocktail.shake()
>>> print (combinations)
>>> ['NC(Br)C(=O)NC(I)C(=O)NCC(=O)O', 'NC(I)C(=O)NC(Br)C(=O)NCC(=O)O']
>>> enumerations = cocktail.enumerate()
>>> print (enumerations)

the output I am getting is a lot longer (192 elements in the list) than the one shown in the example. If needed, I can post the output here on request.

**Comment by Sulstice** [comment]
Ah, so I took a subset of the enumerations and put them in the output. Your code is actually correct and should be outputting 192 enumerations. I've appended a ... in the docs to show that there is technically more
