### ISSUE TITLE
Backbone lengths & proline

### ISSUE THREAD

**Issue by richardjgowers** [Sulstice/cocktail-shaker#167]
https://github.com/Sulstice/cocktail-shaker/blob/master/cocktail_shaker/functional_group_enumerator.py#L61

This line here seems a fragile way of detecting a proline, but then it's also immediately cancelled out two lines below as `peptide_backbone_length` is overwritten.

**Comment by Sulstice** [comment]
Yeah, you're right. I don't why that bug kind of slipped under the radar.  I'll rewrite it a little bit and open a PR.

**Comment by Sulstice** [comment]
Turns out, back then I just had a little misunderstanding of SMILES and how numbers are assigned in the 1D string. Removing the line actually seems like the best solution then detecting for proline and isolating it from regular expression. 

Let me know if that seems to be sufficient!
