### ISSUE TITLE
Installation does not copy datasources directory 

### ISSUE THREAD

**Issue by PatWalters** [Sulstice/cocktail-shaker#34]
I get an error saying that datasources/R_Groups.yaml cannot be found.  It appears that this directory is not being copied to site-packages/cocktail_shaker

**Comment by Sulstice** [comment]
Ah I wondering if ditched the yaml sources for some odd reason or another. I'll work on getting that set up again.

**Comment by Sulstice** [comment]
I nixed the datasources directory, and changed how cocktail shaker will be implemented. Check out the new docs and thank you for letting me know.

Here is the commit of the official nixing of datasources. (Won't be needing it). 

https://github.com/Sulstice/cocktail-shaker/commit/8477ae0b5aa48da801eca30e68b5c3cc5e02fd43
