### ISSUE TITLE
Add command line interface

### ISSUE THREAD

**Issue by cthoyt** [Sulstice/cocktail-shaker#35]
It would be great to have a CLI wrapping this library. I have a lot of experience using click and integrating with setup.py to make a vanity cli command (`cocktail-shaker` would be best) and would be happy to submit a PR if you like the idea

**Comment by Sulstice** [comment]
I thought about adding a CLI! But haven't incorporated it just yet! When I move cocktail shaker to v1.1.0 (a more stable and revamped version) we can perhaps talk more into that?

**Comment by Sulstice** [comment]
Hi @cthoyt  I like the idea and I definitely think it can be a CLI. I wrapped up a lot of the functionality this weekend for 1.1.0 so definitely think this is possible. Check out the readthedocs for the new options within cocktail class object.
