### ISSUE TITLE
Installation doc suggestions

### ISSUE THREAD

**Issue by greglandrum** [Sulstice/cocktail-shaker#93]
some suggestions after reading through the installation docs in `README.md`

- Instead of providing your own (inaccurate) installation instructions for conda, it's better to just point to their installation instructions
- you shouldn't need to provide the path to `conda` when creating a new environment
- you need to activate the new environment before doing the `conda install` of the rdkit or the `pip` install of cocktail-shaker
- I would suggest pointing people to the conda-forge version of the rdkit, not the one from the rdkit channel.
- the line above the example of using pip is an incomplete sentence and has a typo
- if the correct environment is activated, you don't need to provide the path to python (this is for the pip example)
- In the section on "development installation": doing a git clone of the repo will not install cocktail-shaker, it will just clone the repo

Do you need a particular version of the RDKit in order for your tests to pass? If so, I would mention that.

**Comment by Sulstice** [comment]
Ya good point, to me installation is always a tricky conundrum, especially with the conda dependency. I'll point to the RDKit installation setup guide and include that it can be installed via pip.

This ties with making this package conda installable so that might help the installation process.
