### ISSUE TITLE
Maybe include more usage examples

### ISSUE THREAD

**Issue by greglandrum** [Sulstice/cocktail-shaker#95]
This comment comes out of my JOSS review. 
The JOSS reviewer checklist includes:

> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

The Getting Started document only includes a single simple example, so that's not really true here.
I think it'd be worth you fixing this since "Getting Started" docs are valuable resources for people who are using or thinking about using a tool.

**Comment by Sulstice** [comment]
Good suggestion. I actually included more examples within the examples page: https://cocktail-shaker.readthedocs.io/en/latest/guide/examples.html

I'll definitely add more examples ASAP to showcase some additional functionality.

**Comment by Sulstice** [comment]
I added ascii cinema screens, jupyter notebooks as examples to also shed more light on how cocktail works!
