### ISSUE TITLE
No listed dependencies

### ISSUE THREAD

**Issue by greglandrum** [Sulstice/cocktail-shaker#96]
part of my JOSS review:
the guidelines suggest that you should have an explicit list of the cocktail-shaker's dependencies. I don't see this in the documentation and reading setup.py is asking a bit much.

**Comment by Sulstice** [comment]
Yep I'll add it into the documentation, thanks for letting me know (I somehow missed it in their requirements)

**Comment by Sulstice** [comment]
For the requirements, I don't think it would be sufficient to have it in the docs instead I just referenced in the installation where you can find them. 

- setup.py (standard for all python packages)
- requirements.txt (usually people look here for requirements)
- dependency graph (I added a dependency graph using pipdeptree and graphviz) which can be found here: https://github.com/Sulstice/cocktail-shaker/blob/master/dependencies_cocktail_shaker.pdf

Let me know if that satiates that requirement from JOSS. I can also output the deptree into json if that would make it clearer?
